### PR TITLE
initial commit after re-implementing code

### PR DESCRIPTION
**Pull request by mhizterpaul**
I couldn't read the javascript code, I would have loved to refactore it. 
I burned it all down and reimplemented it, In a new branch though, just check out the mhizterpaul branch to see what's new, feel free to merge it, if you like what you see

### CODE REVIEW

**Comment by Dammykeys** [comment]
nice, though i've not check your work yet
i'll surely do
i really appreciate

**Comment by mhizterpaul** [comment]
Appreciate keh? I was looking for something to practise with ni.

**Comment by Dammykeys** [comment]
Your pull request has a bug in it, it replecates the start button

**Comment by mhizterpaul** [comment]
Check what branch you are on, I worked on the Mhizterpaul branch, after you've successfully cloned the repo, you should run `git checkout mhizterpaul` .

**Pull request closed without merging**
